# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dxc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'Alamofire'


  # Pods for dxc

  target 'dxcTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'dxcUITests' do
    # Pods for testing
  end

end
